openapi: "3.0.1"
info:
  title: POSTDATA knowledge graph query system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.0.1"
servers:
  - url: http://62.204.199.252:5005
    description: Production server
  - url: http://localhost:5005/
    description: Test server
paths:
  /book/{title}:
    get:
      summary: Given a book obtain the poetic works
      description: Obtain all the data about the book
      operationId: knowledge_graph_queries.get_book
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
      parameters:
        - name: title
          in: path
          description: Title of the book
          required: true
          schema:
            type: string
          style: simple

  /manifestations:
    get:
      summary: List of all the manifestations
      description: Gets list of all the manifestations
      operationId: knowledge_graph_queries.get_manifestations
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { }

  /poeticWorks:
    get:
      summary: List of all the poeticWorks
      description: Gets list of all the poeticWorks
      operationId: knowledge_graph_queries.get_poeticWorks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object

  /authors:
    get:
      summary: List of all the authors
      description: Gets list of all the authors
      operationId: knowledge_graph_queries.get_authors
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  [
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_juana-ines-de-la-cruz",
                      "birthDate": "1651-11-12T00:00:00Z",
                      "deathDate": "1695-04-17T00:00:00Z",
                      "name": "Juana Inés de la Cruz"
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_antonio-enriquez-gomez",
                      "birthDate": "1600-01-01T00:00:00Z",
                      "deathDate": "1663-01-01T00:00:00Z",
                      "name": "Antonio Enríquez Gómez"
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_san-juan-de-la-cruz",
                      "birthDate": "1542-07-04T00:00:00Z",
                      "deathDate": "1591-12-14T00:00:00Z",
                      "name": "San Juan de la Cruz"
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_gaspar-gil-polo",
                      "birthDate": [
                          "1530-01-01T00:00:00Z",
                          "1540-01-01T00:00:00Z"
                      ],
                      "deathDate": "1591-01-01T00:00:00Z",
                      "name": "Gaspar Gil Polo"
                    }
                  ]

  /author/{name}:
    get:
      description: Search authors by name
      summary: Returns URIs for author resources whose name matches with query
      operationId: knowledge_graph_queries.get_author
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  [
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_juan-de-la-cueva",
                      "name": "Juan de La Cueva",
                      "score": 8.051570892333984
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_san-juan-de-la-cruz",
                      "birthDate": "1542-07-04T00:00:00Z",
                      "deathDate": "1591-12-14T00:00:00Z",
                      "name": "San Juan de la Cruz",
                      "score": 8.051570892333984
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_juan-boscan",
                      "birthDate": "1490-01-01T00:00:00Z",
                      "deathDate": "1542-09-21T00:00:00Z",
                      "name": "Juan Boscán",
                      "score": 7.051570415496826
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_hernando-de-acunya",
                      "name": "Hernando de Acunya",
                      "score": 1
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/p_francisco-de-la-torre",
                      "name": "Francisco de la Torre",
                      "score": 1
                    }
                  ]
    parameters:
      - name: name
        in: path
        description: Name of the author
        required: true
        schema:
          type: string
        style: simple
      - name: limit
        required: false
        description: Maximum number of results
        in: query
        schema:
          type: integer

  /author_profile/{uri}:
    get:
      description: Get all the information related to an author
      summary: Provides personal information and associated works given the URI of an author
      operationId: knowledge_graph_queries.get_author_profile
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "@id": "http://postdata.linhd.uned.es/resource/p_fernando-de-herrera",
                    "birthDate": "1534-01-01T00:00:00Z",
                    "birthPlace": {
                      "@language": "es",
                      "@value": "Sevilla"
                    },
                    "deathDate": "1597-01-01T00:00:00Z",
                    "deathPlace": {
                      "@language": "es",
                      "@value": "Sevilla"
                    },
                    "gender": {
                      "@language": "es",
                      "@value": "masculino"
                    },
                    "name": "Fernando de Herrera",
                    "occupation": [
                      {
                        "@language": "es",
                        "@value": "escritor"
                      },
                      {
                        "@language": "es",
                        "@value": "poeta"
                      },
                      {
                        "@language": "es",
                        "@value": "sacerdote"
                      }
                    ],
                    "portrait": "http://commons.wikimedia.org/wiki/Special:FilePath/Francisco%20pacheco-fernando%20de%20herrera.jpg",
                    "works": [
                      {
                        "@id": "http://postdata.linhd.uned.es/resource/pw_fernando-de-herrera_si-el-presente-dolor-de-vuestra-pena",
                        "roleFunction": "http://postdata.linhd.uned.es/kos/Creator",
                        "title": "Si el presente dolor de vuestra pena"
                      },
                      {
                        "@id": "http://postdata.linhd.uned.es/resource/pw_fernando-de-herrera_inclinen-a-tu-nombre-o-luz-d-espana",
                        "roleFunction": "http://postdata.linhd.uned.es/kos/Creator",
                        "title": "Inclinen a tu nombre, ô luz d' España,"
                      }
                    ]
                  }
    parameters:
      - name: "uri"
        in: path
        description: The URI of an author resource
        required: true
        schema:
          type: string
          format: path
        style: simple

  /poeticWork/{title}:
    get:
      summary: Given a poetic work obtain all the expresions (redactions) of a poetic work and infor about author and books
      description: Given a poetic work obtain all the expresions (redactions) of a poetic work and infor about author and books
      operationId: knowledge_graph_queries.get_poeticWork
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  [
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/pw_luis-de-camoes_alma-y-primero-amor-del-alma-mia",
                      "author": "Luis de Camoes",
                      "name": "Alma y primero amor del alma mía,",
                      "score": 5.3689069747924805
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/pw_alonso-de-ercilla_que-cosa-puede-haber-sin-amor-buena",
                      "author": "Alonso de Ercilla",
                      "name": "¿Qué cosa puede haber sin amor buena?",
                      "score": 4.3689069747924805
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/pw_francisco-de-quevedo_este-amor-que-yo-alimento",
                      "author": "Francisco de Quevedo",
                      "name": "Este amor que yo alimento",
                      "score": 4.3689069747924805
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/pw_fray-luis-de-leon_senor-aquel-amor-por-quien-forzado",
                      "author": "Fray Luis de León",
                      "name": "Señor, aquel amor por quien forzado",
                      "score": 4.3689069747924805
                    },
                    {
                      "@id": "http://postdata.linhd.uned.es/resource/pw_fray-luis-de-leon_al-campo-va-mi-amor-y-va-a-la-aldea",
                      "author": "Fray Luis de León",
                      "name": "Al campo va mi amor, y va a la aldea.",
                      "score": 4.3689069747924805
                    }
                  ]
      parameters:
        - name: title
          in: path
          description: Name of the poeticWork
          required: true
          schema:
            type: string
          style: simple
        - name: limit
          required: false
          description: Maximum number of results
          in: query
          schema:
            type: integer


  /redactions/{uri}:
    get:
      description: Get all the information related to the editions of a poetic work
      summary: Provides contributor information and the available scansions for each textual edition of a poetic work
      operationId: knowledge_graph_queries.get_redactions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "@id": "http://postdata.linhd.uned.es/resource/pw_francisco-de-quevedo_este-amor-que-yo-alimento",
                    "isRealisedThrough": {
                      "@id": "http://postdata.linhd.uned.es/resource/r_francisco-de-quevedo_este-amor-que-yo-alimento_plc",
                      "scansions": [
                        {
                          "@id": "http://postdata.linhd.uned.es/resource/sc_francisco-de-quevedo_este-amor-que-yo-alimento_plc_16376740779860482",
                          "typeOfScansion": "Manual Annotation"
                        },
                        {
                          "@id": "http://postdata.linhd.uned.es/resource/sc_francisco-de-quevedo_este-amor-que-yo-alimento_plc_16376740784785693",
                          "employedTechnique": "http://postdata.linhd.uned.es/kos/CompleteSpanishSyllabification",
                          "typeOfScansion": "Automatic Annotation"
                        }
                      ],
                      "text": "Este amor, que yo alimento\nde mi propio corazón,\nno nace de inclinación,\nsino de conocimiento.\nQue amor de cosa tan bella,\ny gracia, que es infinita,\nsi es elección, me acredita,\nsi no acredita mi estrella.\n¿Y qué deidad me pudiera\ninclinar a que te amara,\nque ese poder no tomara\npara sí, si le tuviera?\nCorrido, señora, escribo\nen el estado presente,\nde que estando de ti ausente,\naún parezca que estoy vivo.\nPues ya en mi pena y pasión,\ndulce Tirsi, tengo hechas\nde las plumas de tus flechas\nlas alas del corazón.\nY sin poder consolarme,\nausente, y amando firme,\nmás hago yo en no morirme,\nque hará el dolor en matarme.\nTanto he llegado a quererte,\nque siento igual pena en mí,\ndel ver, no viéndote a ti,\nque adorándote no verte.\nSi bien recelo, señora,\nque a este amor serás infiel,\npues ser hermosa y cruel\nte pronostica traidora.\nPero traiciones dichosas\nserán, Tirsi, para mí,\npor ver dos caras en ti,\nque han de ser por fuerza hermosas.\nY advierte que en mi pasión,\nse puede tener por cierto,\nque es decir ausente y muerto,\ndos veces una razón."
                    }
                  }
    parameters:
      - name: "uri"
        in: path
        description: The URI of a poetic work resource
        required: true
        schema:
          type: string
          format: path
        style: simple

  /scansion/{uri}:
    get:
      description: Gets all the data associated to a given scansion
      summary: For each scansion, provides structural information for stanzas and lines as well as pattern iormation for the redaction, stanzas and lines. It also includes literary device annotations such enjambment or synalepha.
      operationId: knowledge_graph_queries.get_scansion
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
    parameters:
      - name: "uri"
        in: path
        description: The URI of a scansion resource
        required: true
        schema:
          type: string
          format: path
        style: simple
