openapi: "3.0.1"
info:
  title: POSTDATA knowledge graph query system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.0.1"
servers:
  - url: /
    description: Production server
  - url: http://localhost:5000/
    description: Test server
paths:
  /poeticWorks:
    get:
      summary: List of all the poeticWorks
      description: Gets list of all the poeticWorks
      operationId: knowledge_graph_queries.get_poeticWorks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { "head": { "vars": [ "work", "title", "creator", "date" ] }, "results": { "bindings": [ { "creator": { "type": "literal", "value": "Juana Inés de la Cruz", "xml:lang": "es" }, "title": { "type": "literal", "value": "A estos peñascos rudos", "xml:lang": "es" }, "work": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/pw_juana-ines-de-la-cruz_a-estos-penascos-rudos" } }, { "creator": { "type": "literal", "value": "Antonio Enríquez Gómez", "xml:lang": "es" }, "title": { "type": "literal", "value": "Al son de este arroyuelo, cüyo ronco", "xml:lang": "es" }, "work": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/pw_antonio-enriquez-gomez_al-son-de-este-arroyuelo-cuyo-ronco" } }, { "creator": { "type": "literal", "value": "Juana Inés de la Cruz", "xml:lang": "es" }, "title": { "type": "literal", "value": "Amado dueño mío", "xml:lang": "es" }, "work": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/pw_juana-ines-de-la-cruz_amado-dueno-mio" } }, { "creator": { "type": "literal", "value": "Juana Inés de la Cruz", "xml:lang": "es" }, "title": { "type": "literal", "value": "Amante dulce del alma", "xml:lang": "es" }, "work": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/pw_juana-ines-de-la-cruz_amante-dulce-del-alma" } } ] } }

  /authors:
    get:
      summary: List of all the authors
      description: Gets list of all the authors
      operationId: knowledge_graph_queries.get_authors
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { "head": { "vars": [ "person", "name", "deathDate", "birthDate" ] }, "results": { "bindings": [ { "name": { "type": "literal", "value": "Juana Inés de la Cruz", "xml:lang": "es" }, "person": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/p_juana-ines-de-la-cruz" } }, { "name": { "type": "literal", "value": "Antonio Enríquez Gómez", "xml:lang": "es" }, "person": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/p_antonio-enriquez-gomez" } } ] } }

  /manifestations:
    get:
      summary: List of all the manifestations
      description: Gets list of all the manifestations
      operationId: knowledge_graph_queries.get_manifestations
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { }

  /author/{name}:
    get:
      description: Search authors by name
      summary: Returns URIs for author resources whose name matches with query
      operationId: knowledge_graph_queries.get_author
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { "@context": { "fts": "tag:stardog:api:search:", "pdc": "http://postdata.linhd.uned.es/ontology/postdata-core#" }, "@graph": [ { "@id": "http://postdata.linhd.uned.es/resource/p_antonio-enriquez-gomez", "pdc:name": { "@language": "es", "@value": "Antonio Enríquez Gómez" }, "pdc:score": { "@value": 1 } } ] }
    parameters:
      - name: name
        in: path
        description: Name of the author
        required: true
        schema:
          type: string
        style: simple
      - name: limit
        required: false
        description: Maximum number of results
        in: query
        schema:
          type: integer

  /author_profile/{uri}:
    get:
      description: Get all the information related to an author
      summary: Provides personal information and associated works given the URI of an author
      operationId: knowledge_graph_queries.get_author_profile
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
    parameters:
      - name: "uri"
        in: path
        description: The URI of an author resource
        required: true
        schema:
          type: string
          format: path
        style: simple

  /book/{title}:
    get:
      summary: Given a book obtain the poetic works
      description: Obtain all the data about the book
      operationId: knowledge_graph_queries.get_book
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { }
      parameters:
        - name: title
          in: path
          description: Title of the book
          required: true
          schema:
            type: string
          style: simple

  /poeticWork/{title}:
    get:
      summary: Given a poetic work obtain all the expresions (redactions) of a poetic work and infor about author and books
      description: Given a poetic work obtain all the expresions (redactions) of a poetic work and infor about author and books
      operationId: knowledge_graph_queries.get_poeticWork
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { "@context": { "fts": "tag:stardog:api:search:", "kos": "http://postdata.linhd.uned.es/kos/", "pdc": "http://postdata.linhd.uned.es/ontology/postdata-core#" }, "@graph": [ { "@id": "http://postdata.linhd.uned.es/resource/pw_juana-ines-de-la-cruz_a-estos-penascos-rudos", "pdc:author": { "@language": "es", "@value": "Juana Inés de la Cruz" }, "pdc:name": { "@language": "es", "@value": "A estos peñascos rudos" }, "pdc:score": { "@value": 1 } } ] }
      parameters:
        - name: title
          in: path
          description: Name of the poeticWork
          required: true
          schema:
            type: string
          style: simple
        - name: limit
          required: false
          description: Maximum number of results
          in: query
          schema:
            type: integer

  /redactions/{uri}:
    get:
      description: Get all the information related to the editions of a poetic work
      summary: Provides textual information and poetic analysis annotations for the textual editions of a poetic work
      operationId: knowledge_graph_queries.get_redactions
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
    parameters:
      - name: "uri"
        in: path
        description: The URI of a poetic work resource
        required: true
        schema:
          type: string
          format: path
        style: simple

  /scansion_structure/{uri}:
    get:
      description: Gets the basic structure of the scansions available for a given redaction
      summary: For each scansion, provides structural information for stanzas and lines as well as pattern iormation for the redaction, stanzas and lines
      operationId: knowledge_graph_queries.get_scansion_structure
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
    parameters:
      - name: "uri"
        in: path
        description: The URI of a redaction resource
        required: true
        schema:
          type: string
          format: path
        style: simple

  /scansion_line/{uri}:
    get:
      description: Gets detailed structure of a scanned line, including words and more granular units such grammatical syllables, metrical syllables, morae and feet.
      summary: Given a line, returns scansion information related to its constituents
      operationId: knowledge_graph_queries.get_scansion_line
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
    parameters:
      - name: "uri"
        in: path
        description: The URI of a line resource
        required: true
        schema:
          type: string
          format: path
        style: simple
