openapi: "3.0.1"
info:
  title: POSTDATA knowledge graph query system
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.0.1"
servers:
  - url: /
    description: Production server
  - url: http://localhost:5000/
    description: Test server
paths:
  /authors:
    get:
      summary: Gets all of Authors in the kwoledge graph
      operationId: knowledge_graph_queries.get_authors
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                example: { "head": { "vars": [ "person", "name", "deathDate", "birthDate" ] }, "results": { "bindings": [ { "name": { "type": "literal", "value": "Juana Inés de la Cruz", "xml:lang": "es" }, "person": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/p_juana-ines-de-la-cruz" } }, { "name": { "type": "literal", "value": "Antonio Enríquez Gómez", "xml:lang": "es" }, "person": { "type": "uri", "value": "http://postdata.linhd.uned.es/resource/p_antonio-enriquez-gomez" } } ] } }
